-- =====================================================
-- SUPABASE: SUGESTI KEGIATAN
-- Jalankan sekali di Supabase Dashboard -> SQL Editor.
-- Sugesti disimpan terpusat agar semua user authenticated
-- dapat memakai daftar kegiatan yang sama.
-- =====================================================

CREATE TABLE IF NOT EXISTS public.kegiatan_suggestions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage       text NOT NULL DEFAULT 'common' CHECK (stage IN ('common','mixing','filling','steril','visual','kemas')),
  suggestion  text NOT NULL CHECK (char_length(trim(suggestion)) BETWEEN 1 AND 80),
  created_at  timestamptz NOT NULL DEFAULT now(),
  created_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_kegiatan_suggestions_stage_text
  ON public.kegiatan_suggestions (stage, lower(trim(suggestion)));

CREATE INDEX IF NOT EXISTS idx_kegiatan_suggestions_stage
  ON public.kegiatan_suggestions (stage);

ALTER TABLE public.kegiatan_suggestions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated_select_kegiatan_suggestions" ON public.kegiatan_suggestions;
CREATE POLICY "authenticated_select_kegiatan_suggestions"
  ON public.kegiatan_suggestions FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "authenticated_insert_kegiatan_suggestions" ON public.kegiatan_suggestions;
CREATE POLICY "authenticated_insert_kegiatan_suggestions"
  ON public.kegiatan_suggestions FOR INSERT
  WITH CHECK (auth.role() = 'authenticated' AND (created_by IS NULL OR created_by = auth.uid()));

DROP POLICY IF EXISTS "authenticated_delete_kegiatan_suggestions" ON public.kegiatan_suggestions;
CREATE POLICY "authenticated_delete_kegiatan_suggestions"
  ON public.kegiatan_suggestions FOR DELETE
  USING (auth.role() = 'authenticated');

-- Opsional: migrasikan sugesti bawaan/custom yang sudah ada secara manual.
-- Contoh:
-- INSERT INTO public.kegiatan_suggestions(stage, suggestion)
-- VALUES ('mixing','Loading Lot A')
-- ON CONFLICT DO NOTHING;
